### ISSUE TITLE
make a release that supports numpy >2.0 

### ISSUE THREAD

**Issue by AlexAtCCRI** [fitnr/visvalingamwyatt#12]
this would be a good idea to keep this project alive!
great work!

**Comment by fitnr** [comment]
I haven't looked at running this against numpy 2+. Have you tried it manually? Any bugs come up?

**Comment by AlexAtCCRI** [comment]
the tests run fine, have not tested with use in my project yet

**Comment by fitnr** [comment]
New release: https://pypi.org/project/visvalingamwyatt/

**Comment by AlexAtCCRI** [comment]
thanks!
