### ISSUE TITLE
Question about area threshhold

### ISSUE THREAD

**Issue by CareCat** [fitnr/visvalingamwyatt#4]
Hi!
I have a potentially stupid question about the area threshold parameter.

The problem is basically that i don't understand what unit the threshhold parameter is in. Is it a percentage of the original area or is it a fixed number? Should the number be smaller for smaller (by area, not number of points) polygons?

I read through the definition of the algorithm and looked through the source-code briefly but i still can't wrap my head around it. Maybe it can be clarified slightly in the readMe.

Thanks in advance.

**Comment by fitnr** [comment]
The threshold is an absolute value in the units of the geometry. So for geographic coordinates, one will generally use a very small threshold.
