### ISSUE TITLE
Last coordinate

### ISSUE THREAD

**Issue by dezenn** [fitnr/visvalingamwyatt#9]
Thank you for making this repository. Is there a way to keep the last coordinate? So i basically want to keep the first and last coordinate but certaintly I do not want to use the algorithm only in the inner parts since this will result in a wrong simplification. Thanks in advance.

**Comment by fitnr** [comment]
Could you give an minimum example of a sequence of coordinates and the behavior you're seeing?

**Comment by dezenn** [comment]
I use coordinates like for example this [(2,0), (5,1), (3,2), (8,4,), (2,5), (11,6), (3,7), (5,8)]. Now I want to use the code to get a polygonal chain with only 4 remaining coordinates which should include (2,0) and (5,8). So I use the simplifier.simplify(number=4) method. Now what I get is something like [(2,0), (3,2), (8,4), (2,5)]. But the last one should be (5,8). What i noticed is that when I change the return in the by_number method to the following: 
      
```python
def by_number(self, n):
       n = int(n)
       try:
           threshold = self.ordered_thresholds[n]
       except IndexError:
           return self.pts_in
        
        # return the first n points since by_threshold
        # could return more points if the threshold is the same
        # for some points
        return self.by_threshold(threshold)[:n+1]
```

I get the whished result but then I also have to use simplifier.simplify(number=3) to get 4 coordinates back.

**Comment by dezenn** [comment]
So I realized what the problem is. The functions I wanted simplfiy often result in points with the same threshold. Hence the method self.by_threshold(threshold)[:n] does not "see" the last coordinate.
